
PROPERTIES = "properties"
TYPE = "type"
FORMAT = "format"
OBJECT = "object"
ARRAY = "array"
PARAMS = "params"
COOKIE = "cookie"
HEADER = "header"

LENGTH = "$length"
PARENT = "$parent"
JSON = "$json"
INDEX = "$index"
ACTION = "$action"