// Copyright 2018 Kiruba Sankar Swaminathan. All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file.

using System.Globalization;
using System.Text;
using Yaal.Sql;

namespace Yaal.Descriptors;

/// <summary>Emit typed C# source for a precompiled Branch graph.</summary>
public static class BranchCsEmitter
{
    public sealed class CompileResult
    {
        public required List<string> WrittenPaths { get; init; }
    }

    public static CompileResult CompileApi(
        string apiRoot,
        string outDir,
        string @namespace = "Yaal.Generated",
        IEnumerable<string>? listPaths = null)
    {
        var y = new Yaal(apiRoot, debug: true);
        var paths = listPaths?.ToList() ?? DescriptorDiscovery.ListDescriptors(apiRoot);
        var outRoot = Path.GetFullPath(outDir);
        Directory.CreateDirectory(outRoot);

        var registryEntries = new List<(string Key, string ClassName)>();
        var written = new List<string>();

        foreach (var path in paths)
        {
            foreach (var mapper in DescriptorDiscovery.DiscoverOutputMappers(apiRoot, path))
            {
                var branch = y.CreateDescriptor(path, mapper);
                var className = DescriptorDiscovery.PathToClassName(path, mapper);
                var relFile = Path.Combine(path.Replace('/', Path.DirectorySeparatorChar), className + ".g.cs");
                var dest = Path.Combine(outRoot, relFile);
                Directory.CreateDirectory(Path.GetDirectoryName(dest)!);

                var source = EmitDescriptorFile(@namespace, className, branch);
                File.WriteAllText(dest, source);
                written.Add(relFile.Replace('\\', '/'));

                registryEntries.Add((DescriptorDiscovery.RegistryKey(path, mapper), className));
            }
        }

        var registryPath = Path.Combine(outRoot, "YaalDescriptorRegistry.g.cs");
        File.WriteAllText(registryPath, EmitRegistry(@namespace, registryEntries));
        written.Add("YaalDescriptorRegistry.g.cs");

        return new CompileResult { WrittenPaths = written };
    }

    public static string EmitDescriptorFile(string @namespace, string className, Branch branch)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using Yaal.Descriptors;");
        sb.AppendLine("using Yaal.Sql;");
        sb.AppendLine();
        sb.AppendLine($"namespace {@namespace};");
        sb.AppendLine();
        sb.AppendLine($"public static partial class {className}");
        sb.AppendLine("{");
        sb.AppendLine("    public static Branch Descriptor { get; } = ");
        EmitBranch(sb, branch, indent: 2);
        sb.AppendLine(";");
        sb.AppendLine("}");
        return sb.ToString();
    }

    public static string EmitRegistry(string @namespace, IReadOnlyList<(string Key, string ClassName)> entries)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using Yaal.Descriptors;");
        sb.AppendLine();
        sb.AppendLine($"namespace {@namespace};");
        sb.AppendLine();
        sb.AppendLine("public static class YaalDescriptorRegistry");
        sb.AppendLine("{");
        sb.AppendLine("    public static IReadOnlyDictionary<string, Branch> All { get; } =");
        sb.AppendLine("        new Dictionary<string, Branch>(StringComparer.OrdinalIgnoreCase)");
        sb.AppendLine("        {");
        foreach (var (key, className) in entries.OrderBy(e => e.Key, StringComparer.Ordinal))
            sb.AppendLine($"            [{CsString(key)}] = {className}.Descriptor,");
        sb.AppendLine("        };");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitBranch(StringBuilder sb, Branch branch, int indent)
    {
        var pad = new string(' ', indent);
        sb.AppendLine(pad + "new Branch");
        sb.AppendLine(pad + "{");
        EmitProp(sb, indent + 4, "Name", branch.Name);
        EmitProp(sb, indent + 4, "Method", branch.Method);
        EmitProp(sb, indent + 4, "Path", branch.Path);
        EmitProp(sb, indent + 4, "InputType", branch.InputType);
        EmitProp(sb, indent + 4, "OutputType", branch.OutputType);
        if (branch.PartitionBy != null)
            EmitProp(sb, indent + 4, "PartitionBy", branch.PartitionBy);
        if (branch.UseParentRows)
            sb.AppendLine($"{pad}    UseParentRows = true,");
        if (branch.Parameters is { Count: > 0 })
        {
            sb.AppendLine($"{pad}    Parameters = new Dictionary<string, ParamDecl>(StringComparer.OrdinalIgnoreCase)");
            sb.AppendLine($"{pad}    {{");
            foreach (var (k, v) in branch.Parameters.OrderBy(kv => kv.Key, StringComparer.Ordinal))
            {
                sb.Append($"{pad}        [{CsString(k)}] = ");
                EmitParamDecl(sb, v, indent + 8);
                sb.AppendLine(",");
            }
            sb.AppendLine($"{pad}    }},");
        }
        if (branch.Model != null)
        {
            sb.AppendLine($"{pad}    Model = new DescriptorModel");
            sb.AppendLine($"{pad}    {{");
            EmitModelDictProp(sb, indent + 8, "Args", branch.Model.Args);
            EmitModelDictProp(sb, indent + 8, "Payload", branch.Model.Payload);
            EmitModelDictProp(sb, indent + 8, "Output", branch.Model.Output);
            sb.AppendLine($"{pad}    }},");
        }
        if (branch.Twigs is { Count: > 0 })
        {
            sb.AppendLine($"{pad}    Twigs = new List<Twig>");
            sb.AppendLine($"{pad}    {{");
            foreach (var twig in branch.Twigs)
            {
                sb.Append($"{pad}        ");
                EmitTwig(sb, twig, indent + 8);
                sb.AppendLine(",");
            }
            sb.AppendLine($"{pad}    }},");
        }
        if (branch.Branches is { Count: > 0 })
        {
            sb.AppendLine($"{pad}    Branches = new List<Branch>");
            sb.AppendLine($"{pad}    {{");
            foreach (var child in branch.Branches)
            {
                sb.Append($"{pad}        ");
                EmitBranch(sb, child, indent + 8);
                sb.AppendLine(",");
            }
            sb.AppendLine($"{pad}    }},");
        }
        if (branch.Connections is { Count: > 0 })
        {
            sb.Append($"{pad}    Connections = new List<string> {{ ");
            sb.Append(string.Join(", ", branch.Connections.Select(CsString)));
            sb.AppendLine(" },");
        }
        sb.Append(pad + "}");
    }

    private static void EmitTwig(StringBuilder sb, Twig twig, int indent)
    {
        var pad = new string(' ', indent);
        sb.AppendLine("new Twig");
        sb.AppendLine(pad + "{");
        EmitProp(sb, indent + 4, "Connection", twig.Connection);
        if (twig.HasSortDir != null)
            sb.AppendLine($"{pad}    HasSortDir = {(twig.HasSortDir.Value ? "true" : "false")},");
        if (twig.Nullable is { Count: > 0 })
        {
            sb.Append($"{pad}    Nullable = new List<string> {{ ");
            sb.Append(string.Join(", ", twig.Nullable.Select(CsString)));
            sb.AppendLine(" },");
        }
        if (twig.Content.Count > 0)
        {
            sb.AppendLine($"{pad}    Content = new List<SqlToken>");
            sb.AppendLine($"{pad}    {{");
            foreach (var token in twig.Content)
            {
                sb.Append($"{pad}        ");
                EmitToken(sb, token, indent + 8);
                sb.AppendLine(",");
            }
            sb.AppendLine($"{pad}    }},");
        }
        if (twig.Parameters.Count > 0)
        {
            sb.AppendLine($"{pad}    Parameters = new List<ParamDecl>");
            sb.AppendLine($"{pad}    {{");
            foreach (var p in twig.Parameters)
            {
                sb.Append($"{pad}        ");
                EmitParamDecl(sb, p, indent + 8);
                sb.AppendLine(",");
            }
            sb.AppendLine($"{pad}    }},");
        }
        sb.Append(pad + "}");
    }

    private static void EmitToken(StringBuilder sb, SqlToken token, int indent)
    {
        var pad = new string(' ', indent);
        sb.AppendLine("new SqlToken");
        sb.AppendLine(pad + "{");
        EmitProp(sb, indent + 4, "Type", token.Type);
        EmitProp(sb, indent + 4, "Value", token.Value);
        if (token.Group != null)
            sb.AppendLine($"{pad}    Group = {token.Group.Value},");
        if (token.Name != null)
            EmitProp(sb, indent + 4, "Name", token.Name);
        if (token.Nullable)
            sb.AppendLine($"{pad}    Nullable = true,");
        if (token.NullableParameter != null)
            EmitProp(sb, indent + 4, "NullableParameter", token.NullableParameter);
        if (token.Param != null)
            EmitProp(sb, indent + 4, "Param", token.Param);
        if (token.Choices is { Count: > 0 })
        {
            sb.AppendLine($"{pad}    Choices = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)");
            sb.AppendLine($"{pad}    {{");
            foreach (var (k, v) in token.Choices.OrderBy(kv => kv.Key, StringComparer.Ordinal))
                sb.AppendLine($"{pad}        [{CsString(k)}] = {CsString(v)},");
            sb.AppendLine($"{pad}    }},");
        }
        sb.Append(pad + "}");
    }

    private static void EmitParamDecl(StringBuilder sb, ParamDecl decl, int indent)
    {
        var pad = new string(' ', indent);
        sb.AppendLine("new ParamDecl");
        sb.AppendLine(pad + "{");
        EmitProp(sb, indent + 4, "Name", decl.Name);
        EmitProp(sb, indent + 4, "Type", decl.Type);
        if (decl.Required)
            sb.AppendLine($"{pad}    Required = true,");
        if (decl.HasDefault)
        {
            sb.Append($"{pad}    Default = ");
            sb.Append(CsLiteral(decl.Default));
            sb.AppendLine(",");
            sb.AppendLine($"{pad}    HasDefault = true,");
        }
        sb.Append(pad + "}");
    }

    private static void EmitModelDictProp(StringBuilder sb, int indent, string name, Dictionary<string, object?>? dict)
    {
        if (dict == null)
            return;
        var pad = new string(' ', indent);
        sb.AppendLine($"{pad}{name} = {CsDict(dict)},");
    }

    private static void EmitProp(StringBuilder sb, int indent, string name, string value)
    {
        sb.AppendLine($"{new string(' ', indent)}{name} = {CsString(value)},");
    }

    private static string CsString(string value) =>
        "\"" + value.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\r", "\\r").Replace("\n", "\\n").Replace("\t", "\\t") + "\"";

    private static string CsLiteral(object? value) =>
        value switch
        {
            null => "null",
            string s => CsString(s),
            bool b => b ? "true" : "false",
            int i => i.ToString(CultureInfo.InvariantCulture),
            long l => l.ToString(CultureInfo.InvariantCulture),
            double d => d.ToString(CultureInfo.InvariantCulture),
            float f => f.ToString(CultureInfo.InvariantCulture) + "f",
            decimal m => m.ToString(CultureInfo.InvariantCulture) + "m",
            _ => CsString(value.ToString() ?? ""),
        };

    private static string CsDict(Dictionary<string, object?> dict)
    {
        var sb = new StringBuilder();
        sb.Append("new Dictionary<string, object?>(StringComparer.OrdinalIgnoreCase) { ");
        foreach (var (k, v) in dict.OrderBy(kv => kv.Key, StringComparer.Ordinal))
            sb.Append('[').Append(CsString(k)).Append("] = ").Append(CsValue(v)).Append(", ");
        sb.Append('}');
        return sb.ToString();
    }

    private static string CsValue(object? value) =>
        value switch
        {
            null => "null",
            string s => CsString(s),
            bool b => b ? "true" : "false",
            int i => i.ToString(CultureInfo.InvariantCulture),
            long l => l.ToString(CultureInfo.InvariantCulture),
            double d => d.ToString(CultureInfo.InvariantCulture),
            float f => f.ToString(CultureInfo.InvariantCulture) + "f",
            decimal m => m.ToString(CultureInfo.InvariantCulture) + "m",
            Dictionary<string, object?> dict => CsDict(dict),
            IDictionary<string, object?> idict => CsDict(idict.ToDictionary(
                kv => kv.Key, kv => kv.Value, StringComparer.OrdinalIgnoreCase)),
            IList<object?> list => CsList(list),
            IEnumerable<object?> enumerable => CsList(enumerable.ToList()),
            _ => CsString(value.ToString() ?? ""),
        };

    private static string CsList(IList<object?> list)
    {
        var sb = new StringBuilder();
        sb.Append("new List<object?> { ");
        foreach (var item in list)
            sb.Append(CsValue(item)).Append(", ");
        sb.Append('}');
        return sb.ToString();
    }
}
