<!--
Copyright 2018 Kiruba Sankar Swaminathan. All rights reserved.
Use of this source code is governed by a MIT style
license that can be found in the LICENSE file.
-->

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <RootNamespace>Yaal.Drivers</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Yaal\Yaal.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClickHouse.Client" Version="7.14.0" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.11" />
    <PackageReference Include="MySqlConnector" Version="2.6.1" />
    <PackageReference Include="Npgsql" Version="8.0.6" />
  </ItemGroup>

</Project>
